### ISSUE TITLE
Adding new Terms to the database modifies the database but the changes do not appear for the user.

### ISSUE THREAD

**Issue by IrisAmp** [BasicConceptClassification/ClassificationDeveloper#7]

**Comment by brontel** [comment]
Adding a new term has the SUBTERM_OF relationship pointing in the opposite direction:

Example: Adding "Test" Under "Decorated" (which is under BccTop) should result in:

(t:Term {rawTerm: "Test"})-[:SUBTERM_OF]->(parent:Term {rawTerm: "Decorated"})

But instead we get "Test" being the parent of "Decorated"

(t:Term {rawTerm: "Test"})<-[:SUBTERM_OF]-(parent:Term {rawTerm: "Decorated"})

Since getting the tree from Neo4j goes from parent to child, it will not get the new term since it's a different parent, when each term should only have one parent. Other controlled vocabulary/Term modifications should be checked as well, especially if they have the same issue.

**Comment by IrisAmp** [comment]
Fixed in c78c89d190e91a0b17c9d95b7df3103825548187
